from execution.pipelines.models import TeamPipeline, PipelineStage, PipelineInputContract, PipelineStatus

pipeline_instance = TeamPipeline(
    pipeline_id="creative_video_production",
    team_id="creative",
    name="video_production",
    display_name="Video Production Pipeline",
    status=PipelineStatus.ACTIVE,
    input_contract=PipelineInputContract(input_type="standard_task"),
    stages=[
        PipelineStage(
            stage_id="concept",
            name="concept",
            display_name="Concept",
            order=1,
            stage_definition_id="concept_def"
        ),
        PipelineStage(
            stage_id="scripting",
            name="scripting",
            display_name="Scripting",
            order=2,
            stage_definition_id="scripting_def"
        ),
        PipelineStage(
            stage_id="production",
            name="production",
            display_name="Production",
            order=3,
            stage_definition_id="production_def"
        ),
        PipelineStage(
            stage_id="editing",
            name="editing",
            display_name="Editing",
            order=4,
            stage_definition_id="editing_def"
        ),
        PipelineStage(
            stage_id="quality",
            name="quality",
            display_name="Quality",
            order=5,
            stage_definition_id="quality_def"
        ),
        PipelineStage(
            stage_id="delivery",
            name="delivery",
            display_name="Delivery",
            order=6,
            stage_definition_id="delivery_def"
        )
    ]
)
